### PR TITLE
Update README.md markup

### PR DESCRIPTION
**Pull request by ghost**
- update Markdown markup
- fix small mistakes
- add useful reference links

### CODE REVIEW

**Review by nathaneltitane — COMMENTED** [review]
Thank you for your review and corrections!

Why the backtick rather that the single apostrophe when referency the utility names?

you should also know that LDView and ldview (aka ldview-osmesa) are actually two separate utilities.

Also, if i were to put any references, i'd list the official ldraw domain and other official resources.
What does awesome-ldraw do?

**Comment by ghost** [comment]
> Also, if i were to put any references, i'd list the official ldraw domain and other official resources.

Of course, add official links too. But I highly recommends to keep reference link to `AWESOME LDraw` too, at least at the end of *"REFERENCES"* section

> What does awesome-ldraw do?

`AWESOME LDraw` intended to collect all (official & 3rd-party) useful resources related to *LDraw* in single list. Here is discussion thread:

- https://forums.ldraw.org/thread-23692.html

P.S. More about "AWESOME" lists initiative:

- https://github.com/sindresorhus/awesome

**Comment by ghost** [comment]
> Why the backtick rather that the single apostrophe when referency the utility names?

As those CLI utilities has exactly same names as its Shell-files, the best way to show it in any docs using inline code style. This is common rule for describing command line utilities in any docs.

**Comment by ghost** [comment]
Just added one more commit to this pull request with link to LDraw official website.

**Pull request closed without merging**
